// HPACKHuffman.swift
// RFC 7541 Appendix B static Huffman table, used to decode HTTP/2 header literals.
// Pre-sorted longest-first for fast, deterministic compile-time and runtime matching.

import Foundation

struct HPACKHuffmanSymbol: Sendable {
    let code: UInt32
    let length: UInt8
    let byte: UInt8
}

enum HPACKHuffman {
    static let symbols: [HPACKHuffmanSymbol] = [
        HPACKHuffmanSymbol(code: 0x3ffffffc, length: 30, byte: 10),
        HPACKHuffmanSymbol(code: 0x3ffffffd, length: 30, byte: 13),
        HPACKHuffmanSymbol(code: 0x3ffffffe, length: 30, byte: 22),
        HPACKHuffmanSymbol(code: 0xfffffe2, length: 28, byte: 2),
        HPACKHuffmanSymbol(code: 0xfffffe3, length: 28, byte: 3),
        HPACKHuffmanSymbol(code: 0xfffffe4, length: 28, byte: 4),
        HPACKHuffmanSymbol(code: 0xfffffe5, length: 28, byte: 5),
        HPACKHuffmanSymbol(code: 0xfffffe6, length: 28, byte: 6),
        HPACKHuffmanSymbol(code: 0xfffffe7, length: 28, byte: 7),
        HPACKHuffmanSymbol(code: 0xfffffe8, length: 28, byte: 8),
        HPACKHuffmanSymbol(code: 0xfffffe9, length: 28, byte: 11),
        HPACKHuffmanSymbol(code: 0xfffffea, length: 28, byte: 12),
        HPACKHuffmanSymbol(code: 0xfffffeb, length: 28, byte: 14),
        HPACKHuffmanSymbol(code: 0xfffffec, length: 28, byte: 15),
        HPACKHuffmanSymbol(code: 0xfffffed, length: 28, byte: 16),
        HPACKHuffmanSymbol(code: 0xfffffee, length: 28, byte: 17),
        HPACKHuffmanSymbol(code: 0xfffffef, length: 28, byte: 18),
        HPACKHuffmanSymbol(code: 0xffffff0, length: 28, byte: 19),
        HPACKHuffmanSymbol(code: 0xffffff1, length: 28, byte: 20),
        HPACKHuffmanSymbol(code: 0xffffff2, length: 28, byte: 21),
        HPACKHuffmanSymbol(code: 0xffffff3, length: 28, byte: 23),
        HPACKHuffmanSymbol(code: 0xffffff4, length: 28, byte: 24),
        HPACKHuffmanSymbol(code: 0xffffff5, length: 28, byte: 25),
        HPACKHuffmanSymbol(code: 0xffffff6, length: 28, byte: 26),
        HPACKHuffmanSymbol(code: 0xffffff7, length: 28, byte: 27),
        HPACKHuffmanSymbol(code: 0xffffff8, length: 28, byte: 28),
        HPACKHuffmanSymbol(code: 0xffffff9, length: 28, byte: 29),
        HPACKHuffmanSymbol(code: 0xffffffa, length: 28, byte: 30),
        HPACKHuffmanSymbol(code: 0xffffffb, length: 28, byte: 31),
        HPACKHuffmanSymbol(code: 0xffffffc, length: 28, byte: 127),
        HPACKHuffmanSymbol(code: 0xffffffd, length: 28, byte: 220),
        HPACKHuffmanSymbol(code: 0xffffffe, length: 28, byte: 249),
        HPACKHuffmanSymbol(code: 0x7ffffde, length: 27, byte: 203),
        HPACKHuffmanSymbol(code: 0x7ffffdf, length: 27, byte: 204),
        HPACKHuffmanSymbol(code: 0x7ffffe0, length: 27, byte: 211),
        HPACKHuffmanSymbol(code: 0x7ffffe1, length: 27, byte: 212),
        HPACKHuffmanSymbol(code: 0x7ffffe2, length: 27, byte: 214),
        HPACKHuffmanSymbol(code: 0x7ffffe3, length: 27, byte: 221),
        HPACKHuffmanSymbol(code: 0x7ffffe4, length: 27, byte: 222),
        HPACKHuffmanSymbol(code: 0x7ffffe5, length: 27, byte: 223),
        HPACKHuffmanSymbol(code: 0x7ffffe6, length: 27, byte: 241),
        HPACKHuffmanSymbol(code: 0x7ffffe7, length: 27, byte: 244),
        HPACKHuffmanSymbol(code: 0x7ffffe8, length: 27, byte: 245),
        HPACKHuffmanSymbol(code: 0x7ffffe9, length: 27, byte: 246),
        HPACKHuffmanSymbol(code: 0x7ffffea, length: 27, byte: 247),
        HPACKHuffmanSymbol(code: 0x7ffffeb, length: 27, byte: 248),
        HPACKHuffmanSymbol(code: 0x7ffffec, length: 27, byte: 250),
        HPACKHuffmanSymbol(code: 0x7ffffed, length: 27, byte: 251),
        HPACKHuffmanSymbol(code: 0x7ffffee, length: 27, byte: 252),
        HPACKHuffmanSymbol(code: 0x7ffffef, length: 27, byte: 253),
        HPACKHuffmanSymbol(code: 0x7fffff0, length: 27, byte: 254),
        HPACKHuffmanSymbol(code: 0x3ffffe0, length: 26, byte: 192),
        HPACKHuffmanSymbol(code: 0x3ffffe1, length: 26, byte: 193),
        HPACKHuffmanSymbol(code: 0x3ffffe2, length: 26, byte: 200),
        HPACKHuffmanSymbol(code: 0x3ffffe3, length: 26, byte: 201),
        HPACKHuffmanSymbol(code: 0x3ffffe4, length: 26, byte: 202),
        HPACKHuffmanSymbol(code: 0x3ffffe5, length: 26, byte: 205),
        HPACKHuffmanSymbol(code: 0x3ffffe6, length: 26, byte: 210),
        HPACKHuffmanSymbol(code: 0x3ffffe7, length: 26, byte: 213),
        HPACKHuffmanSymbol(code: 0x3ffffe8, length: 26, byte: 218),
        HPACKHuffmanSymbol(code: 0x3ffffe9, length: 26, byte: 219),
        HPACKHuffmanSymbol(code: 0x3ffffea, length: 26, byte: 238),
        HPACKHuffmanSymbol(code: 0x3ffffeb, length: 26, byte: 240),
        HPACKHuffmanSymbol(code: 0x3ffffec, length: 26, byte: 242),
        HPACKHuffmanSymbol(code: 0x3ffffed, length: 26, byte: 243),
        HPACKHuffmanSymbol(code: 0x3ffffee, length: 26, byte: 255),
        HPACKHuffmanSymbol(code: 0x1ffffec, length: 25, byte: 199),
        HPACKHuffmanSymbol(code: 0x1ffffed, length: 25, byte: 207),
        HPACKHuffmanSymbol(code: 0x1ffffee, length: 25, byte: 234),
        HPACKHuffmanSymbol(code: 0x1ffffef, length: 25, byte: 235),
        HPACKHuffmanSymbol(code: 0xffffea, length: 24, byte: 9),
        HPACKHuffmanSymbol(code: 0xffffeb, length: 24, byte: 142),
        HPACKHuffmanSymbol(code: 0xffffec, length: 24, byte: 144),
        HPACKHuffmanSymbol(code: 0xffffed, length: 24, byte: 145),
        HPACKHuffmanSymbol(code: 0xffffee, length: 24, byte: 148),
        HPACKHuffmanSymbol(code: 0xffffef, length: 24, byte: 159),
        HPACKHuffmanSymbol(code: 0xfffff0, length: 24, byte: 171),
        HPACKHuffmanSymbol(code: 0xfffff1, length: 24, byte: 206),
        HPACKHuffmanSymbol(code: 0xfffff2, length: 24, byte: 215),
        HPACKHuffmanSymbol(code: 0xfffff3, length: 24, byte: 225),
        HPACKHuffmanSymbol(code: 0xfffff4, length: 24, byte: 236),
        HPACKHuffmanSymbol(code: 0xfffff5, length: 24, byte: 237),
        HPACKHuffmanSymbol(code: 0x7fffd8, length: 23, byte: 1),
        HPACKHuffmanSymbol(code: 0x7fffd9, length: 23, byte: 135),
        HPACKHuffmanSymbol(code: 0x7fffda, length: 23, byte: 137),
        HPACKHuffmanSymbol(code: 0x7fffdb, length: 23, byte: 138),
        HPACKHuffmanSymbol(code: 0x7fffdc, length: 23, byte: 139),
        HPACKHuffmanSymbol(code: 0x7fffdd, length: 23, byte: 140),
        HPACKHuffmanSymbol(code: 0x7fffde, length: 23, byte: 141),
        HPACKHuffmanSymbol(code: 0x7fffdf, length: 23, byte: 143),
        HPACKHuffmanSymbol(code: 0x7fffe0, length: 23, byte: 147),
        HPACKHuffmanSymbol(code: 0x7fffe1, length: 23, byte: 149),
        HPACKHuffmanSymbol(code: 0x7fffe2, length: 23, byte: 150),
        HPACKHuffmanSymbol(code: 0x7fffe3, length: 23, byte: 151),
        HPACKHuffmanSymbol(code: 0x7fffe4, length: 23, byte: 152),
        HPACKHuffmanSymbol(code: 0x7fffe5, length: 23, byte: 155),
        HPACKHuffmanSymbol(code: 0x7fffe6, length: 23, byte: 157),
        HPACKHuffmanSymbol(code: 0x7fffe7, length: 23, byte: 158),
        HPACKHuffmanSymbol(code: 0x7fffe8, length: 23, byte: 165),
        HPACKHuffmanSymbol(code: 0x7fffe9, length: 23, byte: 166),
        HPACKHuffmanSymbol(code: 0x7fffea, length: 23, byte: 168),
        HPACKHuffmanSymbol(code: 0x7fffeb, length: 23, byte: 174),
        HPACKHuffmanSymbol(code: 0x7fffec, length: 23, byte: 175),
        HPACKHuffmanSymbol(code: 0x7fffed, length: 23, byte: 180),
        HPACKHuffmanSymbol(code: 0x7fffee, length: 23, byte: 182),
        HPACKHuffmanSymbol(code: 0x7fffef, length: 23, byte: 183),
        HPACKHuffmanSymbol(code: 0x7ffff0, length: 23, byte: 188),
        HPACKHuffmanSymbol(code: 0x7ffff1, length: 23, byte: 191),
        HPACKHuffmanSymbol(code: 0x7ffff2, length: 23, byte: 197),
        HPACKHuffmanSymbol(code: 0x7ffff3, length: 23, byte: 231),
        HPACKHuffmanSymbol(code: 0x7ffff4, length: 23, byte: 239),
        HPACKHuffmanSymbol(code: 0x3fffd2, length: 22, byte: 129),
        HPACKHuffmanSymbol(code: 0x3fffd3, length: 22, byte: 132),
        HPACKHuffmanSymbol(code: 0x3fffd4, length: 22, byte: 133),
        HPACKHuffmanSymbol(code: 0x3fffd5, length: 22, byte: 134),
        HPACKHuffmanSymbol(code: 0x3fffd6, length: 22, byte: 136),
        HPACKHuffmanSymbol(code: 0x3fffd7, length: 22, byte: 146),
        HPACKHuffmanSymbol(code: 0x3fffd8, length: 22, byte: 154),
        HPACKHuffmanSymbol(code: 0x3fffd9, length: 22, byte: 156),
        HPACKHuffmanSymbol(code: 0x3fffda, length: 22, byte: 160),
        HPACKHuffmanSymbol(code: 0x3fffdb, length: 22, byte: 163),
        HPACKHuffmanSymbol(code: 0x3fffdc, length: 22, byte: 164),
        HPACKHuffmanSymbol(code: 0x3fffdd, length: 22, byte: 169),
        HPACKHuffmanSymbol(code: 0x3fffde, length: 22, byte: 170),
        HPACKHuffmanSymbol(code: 0x3fffdf, length: 22, byte: 173),
        HPACKHuffmanSymbol(code: 0x3fffe0, length: 22, byte: 178),
        HPACKHuffmanSymbol(code: 0x3fffe1, length: 22, byte: 181),
        HPACKHuffmanSymbol(code: 0x3fffe2, length: 22, byte: 185),
        HPACKHuffmanSymbol(code: 0x3fffe3, length: 22, byte: 186),
        HPACKHuffmanSymbol(code: 0x3fffe4, length: 22, byte: 187),
        HPACKHuffmanSymbol(code: 0x3fffe5, length: 22, byte: 189),
        HPACKHuffmanSymbol(code: 0x3fffe6, length: 22, byte: 190),
        HPACKHuffmanSymbol(code: 0x3fffe7, length: 22, byte: 196),
        HPACKHuffmanSymbol(code: 0x3fffe8, length: 22, byte: 198),
        HPACKHuffmanSymbol(code: 0x3fffe9, length: 22, byte: 228),
        HPACKHuffmanSymbol(code: 0x3fffea, length: 22, byte: 232),
        HPACKHuffmanSymbol(code: 0x3fffeb, length: 22, byte: 233),
        HPACKHuffmanSymbol(code: 0x1fffdc, length: 21, byte: 153),
        HPACKHuffmanSymbol(code: 0x1fffdd, length: 21, byte: 161),
        HPACKHuffmanSymbol(code: 0x1fffde, length: 21, byte: 167),
        HPACKHuffmanSymbol(code: 0x1fffdf, length: 21, byte: 172),
        HPACKHuffmanSymbol(code: 0x1fffe0, length: 21, byte: 176),
        HPACKHuffmanSymbol(code: 0x1fffe1, length: 21, byte: 177),
        HPACKHuffmanSymbol(code: 0x1fffe2, length: 21, byte: 179),
        HPACKHuffmanSymbol(code: 0x1fffe3, length: 21, byte: 209),
        HPACKHuffmanSymbol(code: 0x1fffe4, length: 21, byte: 216),
        HPACKHuffmanSymbol(code: 0x1fffe5, length: 21, byte: 217),
        HPACKHuffmanSymbol(code: 0x1fffe6, length: 21, byte: 227),
        HPACKHuffmanSymbol(code: 0x1fffe7, length: 21, byte: 229),
        HPACKHuffmanSymbol(code: 0x1fffe8, length: 21, byte: 230),
        HPACKHuffmanSymbol(code: 0xfffe6, length: 20, byte: 128),
        HPACKHuffmanSymbol(code: 0xfffe7, length: 20, byte: 130),
        HPACKHuffmanSymbol(code: 0xfffe8, length: 20, byte: 131),
        HPACKHuffmanSymbol(code: 0xfffe9, length: 20, byte: 162),
        HPACKHuffmanSymbol(code: 0xfffea, length: 20, byte: 184),
        HPACKHuffmanSymbol(code: 0xfffeb, length: 20, byte: 194),
        HPACKHuffmanSymbol(code: 0xfffec, length: 20, byte: 224),
        HPACKHuffmanSymbol(code: 0xfffed, length: 20, byte: 226),
        HPACKHuffmanSymbol(code: 0x7fff0, length: 19, byte: 92),
        HPACKHuffmanSymbol(code: 0x7fff1, length: 19, byte: 195),
        HPACKHuffmanSymbol(code: 0x7fff2, length: 19, byte: 208),
        HPACKHuffmanSymbol(code: 0x7ffc, length: 15, byte: 60),
        HPACKHuffmanSymbol(code: 0x7ffd, length: 15, byte: 96),
        HPACKHuffmanSymbol(code: 0x7ffe, length: 15, byte: 123),
        HPACKHuffmanSymbol(code: 0x3ffc, length: 14, byte: 94),
        HPACKHuffmanSymbol(code: 0x3ffd, length: 14, byte: 125),
        HPACKHuffmanSymbol(code: 0x1ff8, length: 13, byte: 0),
        HPACKHuffmanSymbol(code: 0x1ff9, length: 13, byte: 36),
        HPACKHuffmanSymbol(code: 0x1ffa, length: 13, byte: 64),
        HPACKHuffmanSymbol(code: 0x1ffb, length: 13, byte: 91),
        HPACKHuffmanSymbol(code: 0x1ffc, length: 13, byte: 93),
        HPACKHuffmanSymbol(code: 0x1ffd, length: 13, byte: 126),
        HPACKHuffmanSymbol(code: 0xffa, length: 12, byte: 35),
        HPACKHuffmanSymbol(code: 0xffb, length: 12, byte: 62),
        HPACKHuffmanSymbol(code: 0x7fa, length: 11, byte: 39),
        HPACKHuffmanSymbol(code: 0x7fb, length: 11, byte: 43),
        HPACKHuffmanSymbol(code: 0x7fc, length: 11, byte: 124),
        HPACKHuffmanSymbol(code: 0x3f8, length: 10, byte: 33),
        HPACKHuffmanSymbol(code: 0x3f9, length: 10, byte: 34),
        HPACKHuffmanSymbol(code: 0x3fa, length: 10, byte: 40),
        HPACKHuffmanSymbol(code: 0x3fb, length: 10, byte: 41),
        HPACKHuffmanSymbol(code: 0x3fc, length: 10, byte: 63),
        HPACKHuffmanSymbol(code: 0xf8, length: 8, byte: 38),
        HPACKHuffmanSymbol(code: 0xf9, length: 8, byte: 42),
        HPACKHuffmanSymbol(code: 0xfa, length: 8, byte: 44),
        HPACKHuffmanSymbol(code: 0xfb, length: 8, byte: 59),
        HPACKHuffmanSymbol(code: 0xfc, length: 8, byte: 88),
        HPACKHuffmanSymbol(code: 0xfd, length: 8, byte: 90),
        HPACKHuffmanSymbol(code: 0x5c, length: 7, byte: 58),
        HPACKHuffmanSymbol(code: 0x5d, length: 7, byte: 66),
        HPACKHuffmanSymbol(code: 0x5e, length: 7, byte: 67),
        HPACKHuffmanSymbol(code: 0x5f, length: 7, byte: 68),
        HPACKHuffmanSymbol(code: 0x60, length: 7, byte: 69),
        HPACKHuffmanSymbol(code: 0x61, length: 7, byte: 70),
        HPACKHuffmanSymbol(code: 0x62, length: 7, byte: 71),
        HPACKHuffmanSymbol(code: 0x63, length: 7, byte: 72),
        HPACKHuffmanSymbol(code: 0x64, length: 7, byte: 73),
        HPACKHuffmanSymbol(code: 0x65, length: 7, byte: 74),
        HPACKHuffmanSymbol(code: 0x66, length: 7, byte: 75),
        HPACKHuffmanSymbol(code: 0x67, length: 7, byte: 76),
        HPACKHuffmanSymbol(code: 0x68, length: 7, byte: 77),
        HPACKHuffmanSymbol(code: 0x69, length: 7, byte: 78),
        HPACKHuffmanSymbol(code: 0x6a, length: 7, byte: 79),
        HPACKHuffmanSymbol(code: 0x6b, length: 7, byte: 80),
        HPACKHuffmanSymbol(code: 0x6c, length: 7, byte: 81),
        HPACKHuffmanSymbol(code: 0x6d, length: 7, byte: 82),
        HPACKHuffmanSymbol(code: 0x6e, length: 7, byte: 83),
        HPACKHuffmanSymbol(code: 0x6f, length: 7, byte: 84),
        HPACKHuffmanSymbol(code: 0x70, length: 7, byte: 85),
        HPACKHuffmanSymbol(code: 0x71, length: 7, byte: 86),
        HPACKHuffmanSymbol(code: 0x72, length: 7, byte: 87),
        HPACKHuffmanSymbol(code: 0x73, length: 7, byte: 89),
        HPACKHuffmanSymbol(code: 0x74, length: 7, byte: 106),
        HPACKHuffmanSymbol(code: 0x75, length: 7, byte: 107),
        HPACKHuffmanSymbol(code: 0x76, length: 7, byte: 113),
        HPACKHuffmanSymbol(code: 0x77, length: 7, byte: 118),
        HPACKHuffmanSymbol(code: 0x78, length: 7, byte: 119),
        HPACKHuffmanSymbol(code: 0x79, length: 7, byte: 120),
        HPACKHuffmanSymbol(code: 0x7a, length: 7, byte: 121),
        HPACKHuffmanSymbol(code: 0x7b, length: 7, byte: 122),
        HPACKHuffmanSymbol(code: 0x14, length: 6, byte: 32),
        HPACKHuffmanSymbol(code: 0x15, length: 6, byte: 37),
        HPACKHuffmanSymbol(code: 0x16, length: 6, byte: 45),
        HPACKHuffmanSymbol(code: 0x17, length: 6, byte: 46),
        HPACKHuffmanSymbol(code: 0x18, length: 6, byte: 47),
        HPACKHuffmanSymbol(code: 0x19, length: 6, byte: 51),
        HPACKHuffmanSymbol(code: 0x1a, length: 6, byte: 52),
        HPACKHuffmanSymbol(code: 0x1b, length: 6, byte: 53),
        HPACKHuffmanSymbol(code: 0x1c, length: 6, byte: 54),
        HPACKHuffmanSymbol(code: 0x1d, length: 6, byte: 55),
        HPACKHuffmanSymbol(code: 0x1e, length: 6, byte: 56),
        HPACKHuffmanSymbol(code: 0x1f, length: 6, byte: 57),
        HPACKHuffmanSymbol(code: 0x20, length: 6, byte: 61),
        HPACKHuffmanSymbol(code: 0x21, length: 6, byte: 65),
        HPACKHuffmanSymbol(code: 0x22, length: 6, byte: 95),
        HPACKHuffmanSymbol(code: 0x23, length: 6, byte: 98),
        HPACKHuffmanSymbol(code: 0x24, length: 6, byte: 100),
        HPACKHuffmanSymbol(code: 0x25, length: 6, byte: 102),
        HPACKHuffmanSymbol(code: 0x26, length: 6, byte: 103),
        HPACKHuffmanSymbol(code: 0x27, length: 6, byte: 104),
        HPACKHuffmanSymbol(code: 0x28, length: 6, byte: 108),
        HPACKHuffmanSymbol(code: 0x29, length: 6, byte: 109),
        HPACKHuffmanSymbol(code: 0x2a, length: 6, byte: 110),
        HPACKHuffmanSymbol(code: 0x2b, length: 6, byte: 112),
        HPACKHuffmanSymbol(code: 0x2c, length: 6, byte: 114),
        HPACKHuffmanSymbol(code: 0x2d, length: 6, byte: 117),
        HPACKHuffmanSymbol(code: 0x0, length: 5, byte: 48),
        HPACKHuffmanSymbol(code: 0x1, length: 5, byte: 49),
        HPACKHuffmanSymbol(code: 0x2, length: 5, byte: 50),
        HPACKHuffmanSymbol(code: 0x3, length: 5, byte: 97),
        HPACKHuffmanSymbol(code: 0x4, length: 5, byte: 99),
        HPACKHuffmanSymbol(code: 0x5, length: 5, byte: 101),
        HPACKHuffmanSymbol(code: 0x6, length: 5, byte: 105),
        HPACKHuffmanSymbol(code: 0x7, length: 5, byte: 111),
        HPACKHuffmanSymbol(code: 0x8, length: 5, byte: 115),
        HPACKHuffmanSymbol(code: 0x9, length: 5, byte: 116),
    ]

    /// Decodes a Huffman-coded literal (RFC 7541 §5.2).
    static func decode(_ data: Data) -> String? {
        var output = [UInt8]()
        output.reserveCapacity(data.count * 2)

        var pending: UInt32 = 0
        var pendingBits: Int = 0

        for byte in data {
            pending = (pending << 8) | UInt32(byte)
            pendingBits += 8
            while pendingBits >= 5 {
                guard let symbol = match(pending: pending, bits: pendingBits) else { return nil }
                output.append(symbol.byte)
                pendingBits -= Int(symbol.length)
                pending &= (UInt32(1) << pendingBits) - 1
            }
        }

        // Trailing padding must be a prefix of EOS (all ones).
        if pendingBits > 0 {
            let mask = (UInt32(1) << pendingBits) - 1
            guard pending & mask == mask else { return nil }
        }

        return String(bytes: output, encoding: .utf8)
    }

    private static func match(pending: UInt32, bits: Int) -> HPACKHuffmanSymbol? {
        for symbol in symbols {
            guard Int(symbol.length) <= bits else { continue }
            let shift = bits - Int(symbol.length)
            let mask = (UInt32(1) << Int(symbol.length)) - 1
            if (pending >> shift) & mask == symbol.code { return symbol }
        }
        return nil
    }
}
